### ISSUE TITLE
Allow WordLists to be combined

### ISSUE THREAD

**Issue by wom-bat** [pmaher86/blacksquare#14]
If I want to make a thematic crossword, then I'd like to be able to provide a list of words to be used preferentially, but if none fit, then the fill() function should use the default list.  Easiest way to do this (I think) would be to enable WordLists to be merged: if all the scores to the preferred words are '1', then they're most likely to be chosen (I think).

So for a Hamlet-themed crossword you could do
```
hamletwords = [ "Hamlet", "Polonius", "ghost", "murdermostfoul" , "tobeornottobe", ...]
hamletWordlist = WordList(hamletwords)
xw.fill(word_list= hamletWordList + DEFAULT_WORD_LIST)
```
or similar. (this assumes overloading `+`, but one could use a function instead.)

**Comment by pmaher86** [comment]
Good suggestion, implemented in v0.4.0.
