### ISSUE TITLE
Fill without symmetry?

### ISSUE THREAD

**Issue by ChronoDK** [pmaher86/blacksquare#25]
Is it possible to fill a grid without forcing symmetry? I would like to define the black cells myself, like xw[0,1] = BLACK but when I do so, extra black cells are added to keep the grid symmetrical. I would really like the grid to be defined by my design instead, which is not symmetrical.

**Comment by pmaher86** [comment]
Yes, this is supported. Just set `xw.symmetry=None`. Other symmetry modes like mirror symmetry are also supported.

**Comment by ChronoDK** [comment]
It happens every time there is a 1 cell space.

**Comment by pmaher86** [comment]
Thanks for the find. This is now fixed v0.7.0. In general testing for grids that don't conform to standard American rules (every cell must be part of a word across and down) isn't as robust so let me know if you run into other issues

**Comment by ChronoDK** [comment]
Seems to work perfectly now - great work! Thanks for fixing it so fast 🥇
