### ISSUE TITLE
Bottom right corner of grid bug

### ISSUE THREAD

**Issue by ChronoDK** [pmaher86/blacksquare#27]
It seems there is a problem with the bottom right corner of the grid. If you create a 5x5 grid with only a word in the right most column, and black cells everywhere else, you cannot fill() to get a valid crossword object. None is returned. If you add a letter to the bottom cell in the second to last column, everything works again. It's like that bottom right cell can't be connected to only one word maybe?

**Comment by pmaher86** [comment]
Can you provide code that produces this? I don't see an issue when I run
```python
xw = Crossword(5, symmetry=None)
for i in range(5):
    for j in range(4):
        xw[i,j] = BLACK
xw.fill()
```

**Comment by ChronoDK** [comment]
You need to put in a word in the last column to get the error. I know the grid is filled already that way, but I need to call fill() anyway to setup the xw object.

**Comment by pmaher86** [comment]
Can you please provide some code that reproduces the issue? I'm not sure I understand what you mean. The following also seems to work:
```python
xw = Crossword(5, symmetry=None)
for i in range(5):
    for j in range(4):
        xw[i,j] = BLACK
xw[DOWN, 1] = "WORD "
xw2 = xw.fill()
xw2.fill()
```

**Comment by ChronoDK** [comment]
`xw = Crossword(num_rows=5, num_cols=5)
 xw.symmetry = None
 for i in range(5):
     for j in range(4):
         xw[i,j] = BLACK
     xw[i,4] = "A"
 xw2 = xw.fill()`
 
 xw2 is None here.

**Comment by pmaher86** [comment]
Thanks. The issue was with how the dependency graph of open words was maintained when setting one cell at a time. Just put in a fix.

**Comment by ChronoDK** [comment]
Awesome! Thanks for fixing - I'm again amazed at how well maintained this library is!
